# Build settings
[build]
command = "pnpm build"
publish = "dist"

[build.environment]
NODE_VERSION = "22"

# Headers
[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

# Let Netlify auto-detect functions
[functions]
directory = ".netlify/functions-internal/server"
